Set objShell = CreateObject("Wscript.Shell")
WScript.Sleep 5000
objShell.SendKeys "a"
objShell.SendKeys "e"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "e"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "e"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "r"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "m"
objShell.SendKeys "e"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "e"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "e"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "q"
WScript.Sleep 320
objShell.SendKeys "w"
WScript.Sleep 320
objShell.SendKeys "n"
objShell.SendKeys "e"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "e"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "e"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "r"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "b"
objShell.SendKeys "t"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "r"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "e"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "w"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "v"
objShell.SendKeys "Q"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "q"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "q"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "w"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "c"
objShell.SendKeys "q"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "q"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "q"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "t"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "x"
objShell.SendKeys "q"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "q"
WScript.Sleep 320
objShell.SendKeys "w"
WScript.Sleep 320
objShell.SendKeys "e"
WScript.Sleep 320
objShell.SendKeys "w"
WScript.Sleep 80
objShell.SendKeys "e"
WScript.Sleep 80
objShell.SendKeys "w"
WScript.Sleep 80
objShell.SendKeys "q"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "b"
objShell.SendKeys "q"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "q"
WScript.Sleep 320
objShell.SendKeys "w"
WScript.Sleep 320
objShell.SendKeys "e"
WScript.Sleep 320
objShell.SendKeys "w"
WScript.Sleep 80
objShell.SendKeys "e"
WScript.Sleep 80
objShell.SendKeys "w"
WScript.Sleep 80
objShell.SendKeys "q"
WScript.Sleep 320
objShell.SendKeys "w"
WScript.Sleep 320
objShell.SendKeys "E"
objShell.SendKeys "d"
objShell.SendKeys "a"
objShell.SendKeys "z"
WScript.Sleep 320
objShell.SendKeys "b"
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "E"
objShell.SendKeys "d"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "E"
objShell.SendKeys "d"
objShell.SendKeys "a"
objShell.SendKeys "z"
WScript.Sleep 320
objShell.SendKeys "b"
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "r"
objShell.SendKeys "s"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "E"
objShell.SendKeys "d"
objShell.SendKeys "m"
WScript.Sleep 320
objShell.SendKeys "b"
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "e"
objShell.SendKeys "s"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "e"
objShell.SendKeys "d"
objShell.SendKeys "m"
WScript.Sleep 320
objShell.SendKeys "b"
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "q"
objShell.SendKeys "a"
WScript.Sleep 320
objShell.SendKeys "w"
WScript.Sleep 320
objShell.SendKeys "e"
objShell.SendKeys "d"
objShell.SendKeys "n"
WScript.Sleep 320
objShell.SendKeys "g"
objShell.SendKeys "c"
WScript.Sleep 320
objShell.SendKeys "e"
objShell.SendKeys "a"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "e"
objShell.SendKeys "d"
objShell.SendKeys "n"
WScript.Sleep 320
objShell.SendKeys "g"
objShell.SendKeys "c"
WScript.Sleep 320
objShell.SendKeys "e"
objShell.SendKeys "a"
WScript.Sleep 320
objShell.SendKeys "r"
WScript.Sleep 320
objShell.SendKeys "b"
objShell.SendKeys "g"
objShell.SendKeys "t"
WScript.Sleep 320
objShell.SendKeys "g"
objShell.SendKeys "c"
WScript.Sleep 320
objShell.SendKeys "q"
objShell.SendKeys "a"
objShell.SendKeys "z"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "t"
objShell.SendKeys "b"
WScript.Sleep 320
objShell.SendKeys "r"
WScript.Sleep 80
objShell.SendKeys "t"
objShell.SendKeys "c"
WScript.Sleep 80
objShell.SendKeys "r"
WScript.Sleep 80
objShell.SendKeys "e"
objShell.SendKeys "a"
WScript.Sleep 320
objShell.SendKeys "w"
WScript.Sleep 320
objShell.SendKeys "q"
objShell.SendKeys "a"
objShell.SendKeys "v"
WScript.Sleep 320
objShell.SendKeys "g"
objShell.SendKeys "z"
WScript.Sleep 320
objShell.SendKeys "q"
objShell.SendKeys "n"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "q"
objShell.SendKeys "a"
objShell.SendKeys "v"
WScript.Sleep 320
objShell.SendKeys "g"
objShell.SendKeys "z"
WScript.Sleep 320
objShell.SendKeys "t"
objShell.SendKeys "g"
objShell.SendKeys "n"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "q"
objShell.SendKeys "a"
objShell.SendKeys "c"
WScript.Sleep 320
objShell.SendKeys "a"
objShell.SendKeys "z"
WScript.Sleep 320
objShell.SendKeys "t"
objShell.SendKeys "b"
WScript.Sleep 320
objShell.SendKeys "r"
WScript.Sleep 320
objShell.SendKeys "e"
objShell.SendKeys "c"
WScript.Sleep 320
objShell.SendKeys "w"
WScript.Sleep 80
objShell.SendKeys "e"
objShell.SendKeys "z"
WScript.Sleep 80
objShell.SendKeys "w"
WScript.Sleep 80
objShell.SendKeys "q"
objShell.SendKeys "b"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "q"
objShell.SendKeys "a"
objShell.SendKeys "x"
WScript.Sleep 320
objShell.SendKeys "g"
objShell.SendKeys "n"
WScript.Sleep 320
objShell.SendKeys "q"
objShell.SendKeys "v"
WScript.Sleep 320
objShell.SendKeys "w"
WScript.Sleep 320
objShell.SendKeys "e"
objShell.SendKeys "x"
WScript.Sleep 320 
objShell.SendKeys "w"
WScript.Sleep 80
objShell.SendKeys "e"
objShell.SendKeys "n"
WScript.Sleep 80
objShell.SendKeys "w"
WScript.Sleep 80
objShell.SendKeys "q"
objShell.SendKeys "b"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "q"
objShell.SendKeys "a"
objShell.SendKeys "b"
WScript.Sleep 320
objShell.SendKeys "g"
objShell.SendKeys "v"
WScript.Sleep 320
objShell.SendKeys "q"
objShell.SendKeys "b"
WScript.Sleep 320
objShell.SendKeys "t"
objShell.SendKeys "v"
WScript.Sleep 320
objShell.SendKeys "r"
objShell.SendKeys "b"
WScript.Sleep 320
objShell.SendKeys "e"
WScript.Sleep 80
objShell.SendKeys "r"
objShell.SendKeys "v"
WScript.Sleep 80
objShell.SendKeys "e"
WScript.Sleep 80
objShell.SendKeys "w"
objShell.SendKeys "m"
WScript.Sleep 960
objShell.SendKeys "q"
objShell.SendKeys "e"
objShell.SendKeys "a"
WScript.Sleep 320
objShell.SendKeys "bg"
WScript.Sleep 320
objShell.SendKeys "ec"
WScript.Sleep 320
objShell.SendKeys "bg"
WScript.Sleep 320
objShell.SendKeys "qea"
WScript.Sleep 320
objShell.SendKeys "bg"
WScript.Sleep 320
objShell.SendKeys "rx"
WScript.Sleep 320
objShell.SendKeys "bg"
WScript.Sleep 320
objShell.SendKeys "qedm"
WScript.Sleep 320
objShell.SendKeys "nh"
WScript.Sleep 320
objShell.SendKeys "ex"
WScript.Sleep 320
objShell.SendKeys "nh"
WScript.Sleep 320
objShell.SendKeys "qedc"
WScript.Sleep 320
objShell.SendKeys "gm"
WScript.Sleep 320
objShell.SendKeys "qb"
WScript.Sleep 320
objShell.SendKeys "wm"
WScript.Sleep 320
objShell.SendKeys "qedn"
WScript.Sleep 320
objShell.SendKeys "hc"
WScript.Sleep 320
objShell.SendKeys "ez"
WScript.Sleep 320
objShell.SendKeys "hc"
WScript.Sleep 320
objShell.SendKeys "qedn"
WScript.Sleep 320
objShell.SendKeys "hc"
WScript.Sleep 320
objShell.SendKeys "rz"
WScript.Sleep 320
objShell.SendKeys "hc"
WScript.Sleep 320
objShell.SendKeys "tqgb"
WScript.Sleep 320
objShell.SendKeys "qc"
WScript.Sleep 320
objShell.SendKeys "qazm"
WScript.Sleep 320
objShell.SendKeys "c"
WScript.Sleep 320
objShell.SendKeys "tgb"
WScript.Sleep 320
objShell.SendKeys "rf"
WScript.Sleep 80
objShell.SendKeys "tgc"
WScript.Sleep 80
objShell.SendKeys "rf"
WScript.Sleep 80
objShell.SendKeys "eda"
WScript.Sleep 320
objShell.SendKeys "ws"
WScript.Sleep 320
objShell.SendKeys "qav"
WScript.Sleep 320
objShell.SendKeys "gz"
WScript.Sleep 320
objShell.SendKeys "qav"
WScript.Sleep 320
objShell.SendKeys "gz"
WScript.Sleep 320
objShell.SendKeys "qab"
WScript.Sleep 320
objShell.SendKeys "gz"
WScript.Sleep 320
objShell.SendKeys "tn"
WScript.Sleep 640
objShell.SendKeys "qazc"
WScript.Sleep 320
objShell.SendKeys "z"
WScript.Sleep 320
objShell.SendKeys "tgb"
WScript.Sleep 320
objShell.SendKeys "rz"
WScript.Sleep 320
objShell.SendKeys "edc"
WScript.Sleep 320
objShell.SendKeys "ws"
WScript.Sleep 80
objShell.SendKeys "edz"
WScript.Sleep 80
objShell.SendKeys "ws"
WScript.Sleep 80
objShell.SendKeys "qab"
WScript.Sleep 320
objShell.SendKeys "gz"
WScript.Sleep 320
objShell.SendKeys "qax"
WScript.Sleep 320
objShell.SendKeys "gz"
WScript.Sleep 320
objShell.SendKeys "qv"
WScript.Sleep 320
objShell.SendKeys "wn"
WScript.Sleep 320
objShell.SendKeys "edc"
WScript.Sleep 320
objShell.SendKeys "ws"
WScript.Sleep 80
objShell.SendKeys "ed"
WScript.Sleep 80
objShell.SendKeys "ws"
WScript.Sleep 80
objShell.SendKeys "qa"
WScript.Sleep 320
objShell.SendKeys "g"
WScript.Sleep 320
objShell.SendKeys "qab"
WScript.Sleep 320
objShell.SendKeys "gv"
WScript.Sleep 320
objShell.SendKeys "qaz"
WScript.Sleep 320
objShell.SendKeys "tg"
WScript.Sleep 320
objShell.SendKeys "rf"
WScript.Sleep 320
objShell.SendKeys "ed"
WScript.Sleep 80
objShell.SendKeys "rf"
WScript.Sleep 80
objShell.SendKeys "ed"
WScript.Sleep 80
objShell.SendKeys "ws"
WScript.Sleep 320
objShell.SendKeys "qa"
WScript.Sleep 320
objShell.SendKeys "qaz"
WScript.Sleep 320
objShell.SendKeys "b"
WScript.Sleep 320
objShell.SendKeys "D"
WScript.Sleep 320
objShell.SendKeys "b"
WScript.Sleep 320
objShell.SendKeys "D"
WScript.Sleep 320
objShell.SendKeys "b"
WScript.Sleep 640
objShell.SendKeys "z"
WScript.Sleep 80
objShell.SendKeys "c"
WScript.Sleep 80
objShell.SendKeys "b"
WScript.Sleep 80
objShell.SendKeys "a"